### ISSUE TITLE
Test failed

### ISSUE THREAD

**Issue by leduyquang753** [djfun/mc-map-item-tool#33]
`

PS D:\mcmaptool> npm test

> minecraft-map-item-tool@1.8.0 test D:\mcmaptool
> gulp test
[09:21:23] Using gulpfile D:\mcmaptool\gulpfile.js
[09:21:23] Starting 'clean'...
[09:21:23] Finished 'clean' after 8.45 ms
[09:21:23] Starting 'default'...
[09:21:23] Finished 'default' after 411 ms
[09:21:23] Starting 'test:server'...
[09:21:23] Starting 'test:client'...
events.js:137
      throw er; // Unhandled 'error' event
      ^
Error: spawn casperjs ENOENT
    at _errnoException (util.js:1003:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:389:16)
    at process._tickCallback (internal/process/next_tick.js:152:19)
npm ERR! Test failed.  See above for more details.

`

That was what I got when I went to step 4.

What happened and threw the error?

**Comment by adidenkov** [comment]
Had a similar error, which I managed to resolve by installing `casperjs` globally and `gulp-casperjs` locally, i.e.:
```bash
npm install -g casperjs
npm install gulp-casperjs
```
Also, make sure you can launch `casperjs` in the terminal after the install.
