### ISSUE TITLE
1.20.2 - Giving the map causes an error

### ISSUE THREAD

**Issue by Quadragintillion** [djfun/mc-map-item-tool#84]
java.lang.IllegalArgumentException: Invalid map dimension: null
        at net.minecraft.world.level.saveddata.maps.WorldMap.lambda$3(WorldMap.java:132) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3900-Spigot-a0f3d48-dc45a67]
        at java.util.Optional.orElseGet(Optional.java:364) ~[?:?]
        at net.minecraft.world.level.saveddata.maps.WorldMap.b(WorldMap.java:115) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3900-Spigot-a0f3d48-dc45a67]
        at net.minecraft.world.level.storage.WorldPersistentData.a(SourceFile:70) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3900-Spigot-a0f3d48-dc45a67]
        at net.minecraft.world.level.storage.WorldPersistentData.b(SourceFile:57) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3900-Spigot-a0f3d48-dc45a67]
        at net.minecraft.server.level.WorldServer.a(WorldServer.java:1474) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3900-Spigot-a0f3d48-dc45a67]
        at net.minecraft.world.item.ItemWorldMap.a(ItemWorldMap.java:63) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3900-Spigot-a0f3d48-dc45a67]
        at net.minecraft.world.item.ItemWorldMap.a(ItemWorldMap.java:70) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3900-Spigot-a0f3d48-dc45a67]
        at net.minecraft.world.item.ItemWorldMap.a(ItemWorldMap.java:328) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3900-Spigot-a0f3d48-dc45a67]
        at net.minecraft.world.item.ItemStack.a(ItemStack.java:719) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3900-Spigot-a0f3d48-dc45a67]
        at net.minecraft.world.entity.player.PlayerInventory.j(PlayerInventory.java:329) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3900-Spigot-a0f3d48-dc45a67]
        at net.minecraft.world.entity.player.EntityHuman.b_(EntityHuman.java:554) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3900-Spigot-a0f3d48-dc45a67]
        at net.minecraft.world.entity.EntityLiving.l(EntityLiving.java:2917) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3900-Spigot-a0f3d48-dc45a67]
        at net.minecraft.world.entity.player.EntityHuman.l(EntityHuman.java:272) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3900-Spigot-a0f3d48-dc45a67]
        at net.minecraft.server.level.EntityPlayer.m(EntityPlayer.java:662) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3900-Spigot-a0f3d48-dc45a67]
        at net.minecraft.server.network.PlayerConnection.e(PlayerConnection.java:334) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3900-Spigot-a0f3d48-dc45a67]
        at net.minecraft.network.NetworkManager.d(NetworkManager.java:392) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3900-Spigot-a0f3d48-dc45a67]
        at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:180) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3900-Spigot-a0f3d48-dc45a67]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1310) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3900-Spigot-a0f3d48-dc45a67]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:387) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3900-Spigot-a0f3d48-dc45a67]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1179) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3900-Spigot-a0f3d48-dc45a67]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:996) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3900-Spigot-a0f3d48-dc45a67]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:298) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3900-Spigot-a0f3d48-dc45a67]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by IasonasKalaitzakis** [comment]
Yeah it doesnt work for me either on 1.20.2.

**Comment by robengrobban** [comment]
Can confirm. The issue started to happen in the switch from 1.20.1 to 1.20.2.

**Comment by augstb** [comment]
If it can help,

It seems like the .dat files are missing "DataVersion" entry that must have been added recently I guess.
A dirty fix that works:
Just set it to 3465 or lower (https://minecraft.fandom.com/wiki/Data_version)
it misses 'banners', 'frames' and 'dimension' entries that you could add by hand...

![Capture d'écran 2023-10-22 144220](https://github.com/djfun/mc-map-item-tool/assets/32638090/e5d72f5b-0480-4ab1-8752-543552ccb238)

**Comment by StalePhish** [comment]
Thank you @augstb, you're the hero of the day! 

I had discovered about 70 "corrupted" maps with this "Invalid map dimension: null" message in the server log. I found that a single map had no DataVersion tag, and all of the others had DataVersion: 1631 with 3/31/2019 modified dates. I updated all of these to 3465 and now they are all fixed!
